# Example config for meticulous-worker.
#
# Save this as .cache/meticulous-worker.toml or wherever you specify the config
# file using the --config-file or -c option.

# The host and port of the broker.
#
# Can also be specified via the `--broker` or `-b` command-line options, or via
# the METICULOUS_WORKER_BROKER environment variable.
#
# There is no default. This option must be specified.
broker = localhost:1234

# The number of job slots available. Most jobs will take one job slot.
#
# Can also be specified via the `--slots` or `-s` command-line options, or via
# the METICULOUS_WORKER_SLOTS environment variable.
#
# Default: number of machine cores
http_port = 8888

# The directory used for the cache.
#
# Can also be specified via the `--cache-root` or `-r` command-line options, or
# via the METICULOUS_WORKER_CACHE_ROOT environment variable.
#
# If this directory doesn't exist, the worker will attempt to create it when
# starting.
#
# Default: ".cache/meticulous-worker"
cache_root = ".cache/meticulous-worker"

# The target amount of disk space to use for the cache, in bytes. This bound
# won't be followed strictly, so it's best to be conservative
#
# Can also be specified via the `--cache-bytes-used-target` or `-B`
# command-line options, or via the METICULOUS_WORKER_CACHE_BYTES_USED_TARGET
# environment variable.
#
# Default: 1000000000
cache_bytes_used_target = 1000000000

# The maximum amount of bytes to return inline for captured stdout and stderr.
#
# Can also be specified via the `--inline-limit` or `-i`
# command-line options, or via the METICULOUS_WORKER_INLINE_LIMIT environment
# variable.
#
# Default: 1000000
inline_limit = 1000000
