[package]
name = "meticulous-util"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
meticulous-base = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
