[package]
name = "meticulous-util"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow.workspace = true
bincode.workspace = true
bytesize.workspace = true
clap.workspace = true
fs2.workspace = true
meticulous-base.workspace = true
serde.workspace = true
sha2.workspace = true
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
concat-idents.workspace = true
rand.workspace = true
tokio = { workspace = true, features = ["io-util", "macros", "rt-multi-thread"] }
