[workspace]
resolver = "2"
members = [ "crates/*" ]

[workspace.dependencies]
anyhow = "1.0.71"
bincode = "1.3.3"
clap = { version = "4.2.7", features = ["derive", "string", "wrap_help"] }
console_error_panic_hook = "0.1.7"
eframe = "0.22"
egui = "0.22"
flate2 = "1.0.26"
futures = "0.3"
gethostname = "0.4.2"
gloo-net = "0.4"
gloo-utils = "0.2"
hyper = { version = "0.14", features = ["http1", "server", "tcp"] }
hyper-tungstenite = "0.11"
itertools = "0.10.5"
meticulous-base = { path = "crates/meticulous-base" }
meticulous-test = { path = "crates/meticulous-test" }
meticulous-ui = { path = "crates/meticulous-ui" }
meticulous-util = { path = "crates/meticulous-util" }
nix = { version = "0.26.2", features = ["signal"] }
num_cpus = "1.15.0"
rand = "0.8.5"
regex = "1.8.3"
serde = { version = "1", features = ["derive"] }
sha2 = "0.10.6"
tar = "0.4.38"
tempfile = "3.5.0"
tokio = { version = "1.28" }
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"
