[workspace]
resolver = "2"
members = [ "crates/*" ]

[profile.wasm_dev]
inherits = "dev"

[profile.wasm_release]
inherits = "release"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace.dependencies]
anyhow = "1.0.71"
assert_matches = "1.5.0"
bincode = "1.3.3"
bytesize = "1.3.0"
cargo_metadata = "0.18"
clap = { version = "4.2.7", features = ["derive", "string", "wrap_help"] }
colored = "2.0.4"
concat-idents = "1.1.5"
console = "0.15"
console_error_panic_hook = "0.1.7"
eframe = "0.23"
egui = "0.23"
egui_gauge = "0.1"
egui-toast = "0.9"
enum-map = { version = "2.7.0", features = ["serde"] }
figment = { version = "0.10.10", features = ["env", "toml"] }
futures = "0.3"
gethostname = "0.4.2"
gloo-net = "0.4"
gloo-utils = "0.2"
hyper-tungstenite = "0.11"
hyper = { version = "0.14", features = ["http1", "server", "tcp"] }
indicatif = "0.17"
itertools = "0.10.5"
maplit = "1"
meticulous-base = { path = "crates/meticulous-base" }
meticulous-client = { path = "crates/meticulous-client" }
meticulous-plot = { path = "crates/meticulous-plot" }
meticulous-test = { path = "crates/meticulous-test" }
meticulous-util = { path = "crates/meticulous-util" }
nc = "0.8.18"
nix = { version = "0.26.2", features = ["signal"] }
num_cpus = "1.15.0"
rand = "0.8.5"
regex = "1.8.3"
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1.0.107" }
serde_test = "1"
serial_test = "2.0.0"
sha2 = "0.10.6"
slog = "2.7.0"
slog-async = "2.8.0"
slog-term = "2.9.0"
strum = { version = "0.25.0", features = ["derive"] }
tar = "0.4.38"
tempfile = "3.5.0"
tokio = "1.28"
tuple = "0.5.1"
unicode-truncate = "0.2.0"
unicode-width = "0.1.7"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"
