[workspace]
resolver = "2"
members = [ "crates/*" ]

[profile.wasm_dev]
inherits = "dev"

[profile.wasm_release]
inherits = "release"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
version = "0.4.0-dev"

[workspace.dependencies]
anyhow = "1.0.71"
assert_matches = "1.5.0"
async-compression = { version = "0.4", features = ["tokio", "gzip"] }
bincode = "1.3.3"
bumpalo = { version = "3.14.0", features = ["collections"] }
bytesize = "1.3.0"
combine = "4"
c_str_macro = "1.0.3"
camino = { version = "1.1.6", features = ["serde1"] }
cargo_metadata = "0.18"
clap = { version = "4.2.7", features = ["derive", "string", "wrap_help"] }
chrono = "0.4"
colored = "2.0.4"
concat-idents = "1.1.5"
console = "0.15"
console_error_panic_hook = "0.1.7"
derive_more = "0.99"
directories = "5"
eframe = "0.23"
egui = "0.23"
egui_gauge = "0.1"
egui-toast = "0.9"
enum-map = { version = "2.7.0", features = ["serde"] }
enumset = { version = "1.1.3", features = ["serde"] }
figment = { version = "0.10.10", features = ["env", "toml"] }
fs2 = "0.4"
futures = "0.3"
gethostname = "0.4.2"
globset = "0.4"
gloo-net = "0.4"
gloo-utils = "0.2"
hex = "0.4.3"
hyper-tungstenite = "0.11"
hyper = { version = "0.14", features = ["http1", "server", "tcp"] }
indicatif = { version = "0.17", features = ["in_memory", "tokio"] }
itertools = "0.10.5"
lddtree = "0.3"
maplit = "1"
maelstrom-base = { path = "crates/maelstrom-base" }
maelstrom-broker = { path = "crates/maelstrom-broker" }
maelstrom-client = { path = "crates/maelstrom-client" }
maelstrom-container = { path = "crates/maelstrom-container" }
maelstrom-plot = { path = "crates/maelstrom-plot" }
maelstrom-test = { path = "crates/maelstrom-test" }
maelstrom-util = { path = "crates/maelstrom-util" }
maelstrom-worker = { path = "crates/maelstrom-worker" }
maelstrom-worker-child = { path = "crates/maelstrom-worker-child" }
nc = { version = "0.8.18", default-features = false }
netlink-packet-core = "0.7"
netlink-packet-route = "0.17"
nix = { version = "0.26.2", features = ["signal"] }
nonempty = { version = "0.8.1", features = ["serialize"] }
num = "0.4.1"
num_cpus = "1.15.0"
oci-spec = "0.6"
rand = "0.8.5"
regex = "1.8.3"
regex-macro = "0.2"
reqwest = { version = "0.11", features = [ "stream", "json" ] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1.0.107" }
serde_repr = "0.1"
serde_test = "1"
serde_with = { version = "3.4", features = ["chrono"] }
serial_test = "2.0.0"
sha2 = "0.10.6"
slog = { version = "2.7.0", features = ["max_level_debug", "release_max_level_debug"] }
slog-async = "2.8.0"
slog-term = "2.9.0"
strum = { version = "0.25.0", features = ["derive"] }
tar = "0.4.38"
tempfile = "3.5.0"
tokio = { version = "1.28", features = [ "rt", "rt-multi-thread", "macros", "fs", "io-util" ] }
tokio-util = { version = "0.7.10", features = [ "compat" ] }
toml = "0.8.8"
tuple = "0.5.1"
unicode-truncate = "0.2.0"
unicode-width = "0.1.7"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
wasm-logger = "0.2"
