[[directives]]
include_shared_libraries = true

[[directives]]
filter = "package.equals(maelstrom-worker) && name.starts_with(executor::)"
layers = [{ stubs = [ "/proc/", "/sys/", "/tmp/", "dev/{fuse,full,null,random,tty,urandom,zero}" ] }]

mounts = [
    { fs_type = "tmp", mount_point = "/tmp" },
    { fs_type = "proc", mount_point = "/proc" },
    { fs_type = "sys", mount_point = "/sys" },
]
devices = ["fuse", "full", "null", "random", "tty", "urandom", "zero"]

[[directives]]
filter = """
(package.equals(maelstrom-broker) && name.starts_with(artifact_fetcher::tests)) ||
package.equals(cargo-maelstrom)"""
layers = [{ stubs = ["/proc/", "/tmp/"] }]
mounts = [
    { fs_type = "tmp", mount_point = "/tmp" },
    { fs_type = "proc", mount_point = "/proc" },
]

[[directives]]
filter = "package.equals(maelstrom-client) && test.equals(integration_test)"
layers = [
    { stubs = ["/{proc,tmp}/", "/dev/{null,fuse}"] },
    { paths = ["<build_dir>/maelstrom-client"], canonicalize = true }
]
mounts = [
    { fs_type = "tmp", mount_point = "/tmp" },
    { fs_type = "proc", mount_point = "/proc" },
]
devices = ["null", "fuse"]
environment = { HOME = "/tmp" }

[[directives]]
filter = """
package.equals(maelstrom-client-process) ||
package.equals(maelstrom-container) ||
package.equals(maelstrom-fuse) ||
package.equals(maelstrom-util)"""
layers = [{ stubs = ["/tmp/"] }]
mounts = [ { fs_type = "tmp", mount_point = "/tmp" } ]

[[directives]]
filter = "package.equals(maelstrom-util) && name.equals(io::splicer)"
added_mounts = [
    { fs_type = "proc", mount_point = "/proc" },
]
added_layers = [{ stubs = [ "proc/" ] }]

[[directives]]
filter = """
package.equals(maelstrom-util) && (
    name.equals(config::common::tests::broker_addr_deserialize_from_hostname_string) ||
    name.equals(config::common::tests::broker_addr_from_str)
)"""
[[directives.added_layers]]
paths = [ "crates/maelstrom-util/src/config/hosts" ]
strip_prefix = "crates/maelstrom-util/src/config/"
prepend_prefix = "/etc/"

[[directives]]
filter = "package.equals(maelstrom-fuse) || package.equals(maelstrom-layer-fs)"
mounts = [
    { fs_type = "tmp", mount_point = "/tmp" },
    { fs_type = "proc", mount_point = "/proc" },
]
working_directory = "/root"
added_layers = [{ stubs = [ "root/", "proc/", "tmp/", "dev/fuse", "dev/null" ] }]
added_devices = ["null", "fuse"]

[[directives]]
filter = "package.equals(cargo-maelstrom) && test.equals(integration_test)"
image.name = "rust"
image.use = ["layers", "environment"]
added_layers = [
    { stubs = ["/dev/{fuse,null}"] },
    { paths = ["<build_dir>/client-bg-proc"], canonicalize = true }
]
devices = ["null", "fuse"]
mounts = [
    { fs_type = "tmp", mount_point = "/tmp" },
    { fs_type = "tmp", mount_point = "/root" },
    { fs_type = "proc", mount_point = "/proc" },
]

[[directives]]
added_environment = { RUST_BACKTRACE = "$env{RUST_BACKTRACE:-0}" }
