[[directives]]
include_shared_libraries = true

[[directives]]
filter = "package.equals(maelstrom-worker) && name.starts_with(executor::)"
layers = [{ stubs = [ "/proc/", "/sys/", "/tmp/", "dev/{fuse,full,null,random,tty,urandom,zero}" ] }]

mounts = [
    { fs_type = "tmp", mount_point = "/tmp" },
    { fs_type = "proc", mount_point = "/proc" },
    { fs_type = "sys", mount_point = "/sys" },
]
devices = ["fuse", "full", "null", "random", "tty", "urandom", "zero"]

[[directives]]
filter = "package.equals(maelstrom-broker) && name.starts_with(artifact_fetcher::tests)"
layers = [{ stubs = ["/proc/", "/tmp/"] }]
mounts = [
    { fs_type = "tmp", mount_point = "/tmp" },
    { fs_type = "proc", mount_point = "/proc" },
]

[[directives]]
filter = "package.equals(cargo-maelstrom)"
image.name = "rust"
image.use = ["layers", "environment"]
enable_loopback = true
added_layers = [{ stubs = ["/dev/null"] }]
mounts = [
    { fs_type = "tmp", mount_point = "/tmp" },
    { fs_type = "tmp", mount_point = "/root" },
    { fs_type = "proc", mount_point = "/proc" },
]

[[directives]]
filter = """
package.equals(maelstrom-client) ||
package.equals(maelstrom-client-process) ||
package.equals(maelstrom-container) ||
package.equals(maelstrom-fuse) ||
package.equals(maelstrom-layer-fs) ||
package.equals(maelstrom-util)"""
layers = [{ stubs = ["/tmp/"] }]
mounts = [ { fs_type = "tmp", mount_point = "/tmp" } ]

[[directives]]
filter = "package.equals(maelstrom-fuse) && name.equals(fuser::mnt::test::mount_unmount)"
image.name = "alpine"
image.use = ["layers", "environment"]
mounts = [
    { fs_type = "tmp", mount_point = "/tmp" },
    { fs_type = "proc", mount_point = "/proc" },
]
added_layers = [{ stubs = [ "dev/null" ] }]
added_devices = ["null"]

[[directives]]
filter = "package.equals(maelstrom-fuse) || package.equals(maelstrom-layer-fs)"
added_layers = [{ stubs = [ "dev/fuse" ] }]
added_devices = ["fuse"]

[[directives]]
filter = "package.equals(maelstrom-client) && test.equals(integration_test)"
image.name = "alpine"
image.use = ["layers", "environment"]
enable_loopback = true
mounts = [
    { fs_type = "tmp", mount_point = "/tmp" },
    { fs_type = "tmp", mount_point = "/root" },
    { fs_type = "proc", mount_point = "/proc" },
]

[[directives]]
added_environment = { RUST_BACKTRACE = "$env{RUST_BACKTRACE:-0}" }
