[[groups]]
module = "meticulous-worker"
tests = "executor::"
layers = ["proc-and-tmp.tar"]
devices = ["full", "null", "random", "tty", "urandom", "zero"]
include_shared_libraries = true
[[groups.mounts]]
fs_type = "tmp"
mount_point = "/tmp"
[[groups.mounts]]
fs_type = "proc"
mount_point = "/proc"
[[groups.mounts]]
fs_type = "sys"
mount_point = "/sys"

[[groups]]
module = "meticulous-cargo-test"
tests = "integration_test::"
layers = ["docker:rust", "dev-null.tar"]
[[groups.mounts]]
fs_type = "tmp"
mount_point = "/tmp"
[[groups.mounts]]
fs_type = "tmp"
mount_point = "/root"
[[groups.mounts]]
fs_type = "proc"
mount_point = "/proc"

[[groups]]
module = "meticulous-container"
layers = ["proc-and-tmp.tar"]
include_shared_libraries = true
[[groups.mounts]]
fs_type = "tmp"
mount_point = "/tmp"
