[[directives]]
module = "meticulous-worker"
tests = "executor::"
include_shared_libraries = true
layers = ["proc-and-tmp.tar"]
mounts = [
    { fs_type = "tmp", mount_point = "/tmp" },
    { fs_type = "proc", mount_point = "/proc" },
    { fs_type = "sys", mount_point = "/sys" },
]
devices = ["full", "null", "random", "tty", "urandom", "zero"]

[[directives]]
module = "cargo-metest"
loopback_enabled = true
layers = ["docker:rust", "dev-null.tar"]
mounts = [
    { fs_type = "tmp", mount_point = "/tmp" },
    { fs_type = "tmp", mount_point = "/root" },
    { fs_type = "proc", mount_point = "/proc" },
]

[[directives]]
module = "meticulous-container"
include_shared_libraries = true
layers = ["proc-and-tmp.tar"]
mounts = [ { fs_type = "tmp", mount_point = "/tmp" } ]

[[directives]]
module = "meticulous-client"
include_shared_libraries = true
layers = ["proc-and-tmp.tar"]
mounts = [ { fs_type = "tmp", mount_point = "/tmp" } ]
