[[directives]]
include_shared_libraries = true

[[directives]]
filter = "package.equals(maelstrom-worker) && name.starts_with(executor::)"
layers = ["proc-and-tmp.tar"]
mounts = [
    { fs_type = "tmp", mount_point = "/tmp" },
    { fs_type = "proc", mount_point = "/proc" },
    { fs_type = "sys", mount_point = "/sys" },
]
devices = ["full", "null", "random", "tty", "urandom", "zero"]

[[directives]]
filter = "package.equals(cargo-metest)"
image.name = "rust"
image.use = ["layers", "environment"]
enable_loopback = true
include_shared_libraries = false
added_layers = ["dev-null.tar"]
mounts = [
    { fs_type = "tmp", mount_point = "/tmp" },
    { fs_type = "tmp", mount_point = "/root" },
    { fs_type = "proc", mount_point = "/proc" },
]

[[directives]]
filter = "package.equals(meticulous-container)"
layers = ["proc-and-tmp.tar"]
mounts = [ { fs_type = "tmp", mount_point = "/tmp" } ]

[[directives]]
filter = "package.equals(meticulous-client)"
layers = ["proc-and-tmp.tar"]
mounts = [ { fs_type = "tmp", mount_point = "/tmp" } ]

[[directives]]
added_environment = { RUST_BACKTRACE = "$env{RUST_BACKTRACE:-0}" }
