[package]
name = "meticulous-container"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-compression.workspace = true
clap.workspace = true
directories.workspace = true
futures.workspace = true
indicatif.workspace = true
oci-spec.workspace = true
reqwest.workspace = true
serde_repr = "0.1"
serde.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio-util.workspace = true
tokio.workspace = true
toml.workspace = true
