[package]
name = "maelstrom-client"
categories = ["development-tools::testing", "virtualization"]
description = "Client library for Maelstrom."
keywords = ["cluster", "containers"]
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
maelstrom-client-process.workspace = true

[dev-dependencies]
maelstrom-base.workspace = true
maelstrom-test.workspace = true
maelstrom-util.workspace = true
maplit.workspace = true
nonempty.workspace = true
sha2.workspace = true
tempfile.workspace = true
