# Example config for meticulous-broker.
#
# Save this as .cache/meticulous-broker.toml or wherever you specify the config
# file using the --config-file or -c option.

# The main port to listen on. This is the port used by all clients and workers.
# It is also used for artifact transfers, both to and from the broker.
#
# Can also be specified via the `--port` or `-p` command-line options, or via
# the METICULOUS_BROKER_PORT environment variable.
#
# If `port` is specified as 0, the OS will choose an unused port.
#
# Default:
# port = 0

# The port to use for the web UI.
#
# Can also be specified via the `--http-port` or `-H` command-line options, or
# via the METICULOUS_BROKER_HTTP_PORT environment variable.
#
# If `http_port` is specified as 0, the OS will choose an unused port.
#
# Default:
# http_port = 0

# The directory used for the cache.
#
# Can also be specified via the `--cache-root` or `-r` command-line options, or
# via the METICULOUS_BROKER_CACHE_ROOT environment variable.
#
# If this directory doesn't exist, the broker will attempt to create it when
# starting.
#
# Default:
# cache_root = ".cache/meticulous-broker"

# The target amount of disk space to use for the cache, in bytes. This bound
# won't be followed strictly, so it's best to be conservative
#
# Can also be specified via the `--cache-bytes-used-target` or `-B`
# command-line options, or via the METICULOUS_BROKER_CACHE_BYTES_USED_TARGET
# environment variable.
#
# Default:
# cache_bytes_used_target = 1000000000

# The minimum log level to output.
#
# Can also be specified via the `--log-level` or `-l` command-line options, or
# via the METICULOUS_BROKER_LOG_LEVEL environment variable.
#
# Possibilities: "error", "warning", "info", "debug"
#
# Default:
# log_level = "info"
