[package]
name = "maelstrom-util"
edition.workspace = true
license.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
bincode.workspace = true
bytesize.workspace = true
clap.workspace = true
derive_more.workspace = true
fs2.workspace = true
maelstrom-base.workspace = true
serde.workspace = true
sha2.workspace = true
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
concat-idents.workspace = true
rand.workspace = true
tokio = { workspace = true, features = ["io-util", "macros", "rt-multi-thread"] }
