[package]
name = "meticulous-worker-child"
version = "0.1.0"
edition = "2021"

[dependencies]
nc.workspace = true
tuple.workspace = true
netlink-packet-core.workspace = true
netlink-packet-route.workspace = true

[[bin]]
name = "meticulous-worker-child-test-cli"
path = "src/bin/cli.rs"
