# Example config for maelstrom-run.
#
# Save this as ~/.config/maelstrom/run/config.toml or wherever you specify the
# config file using the --config-file or -c option.

# The host and port of the broker.
#
# Can also be specified via the `--broker` or `-b` command-line options, or via
# the MAELSTROM_RUN_BROKER environment variable.
#
# There is no default. This option must be specified.
#
# Examples:
# broker = "localhost:1234"
# broker = "127.0.0.1:1234"
broker = "[::1]:1234"

# The minimum log level to output.
#
# Can also be specified via the `--log-level` or `-l` command-line options, or
# via the MAELSTROM_RUN_LOG_LEVEL environment variable.
#
# Possibilities: "error", "warning", "info", and "debug"
#
# Default:
# log-level = "info"
#
# Examples:
# log-level = "debug"
