[package]
name = "meticulous-broker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
hyper-tungstenite = { workspace = true }
hyper = { workspace = true }
meticulous-base = { workspace = true }
meticulous-util = { workspace = true }
serde = { workspace = true }
tar = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[dev-dependencies]
itertools = { workspace = true }
meticulous-test = { workspace = true }
