[package]
name = "meticulous-broker"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
hyper-tungstenite = { workspace = true }
hyper = { workspace = true }
meticulous = { workspace = true }
meticulous-ui = { workspace = true }
meticulous-util = { workspace = true }
serde = { workspace = true }
tar = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
itertools = { workspace = true }
