[package]
name = "meticulous-broker"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.7", features = ["derive", "string", "wrap_help"] }
meticulous = { path = "../../library", version = "^0.1" }
meticulous_ui = { path = "../../ui", version = "^0.1" }
tokio = { version = "1.28", features = ["full"] }
futures = "^0.3"
hyper = { version = "^0.14", features = ["http1", "server", "tcp"] }
hyper-tungstenite = "^0.11"
tar = "0.4.38"
serde = { version = "1", features = ["derive"] }
bincode = "1.3.3"
itertools = "0.10.5"
