# Example config for maelstrom-broker.
#
# Save this as ~/.config/maelstrom/broker/config.toml or wherever you specify
# the config file using the --config-file or -c option.

# The main port to listen on. This is the port used by all clients and workers.
# It is also used for artifact transfers, both to and from the broker.
#
# Can also be specified via the `--port` or `-p` command-line options, or via
# the MAELSTROM_BROKER_PORT environment variable.
#
# If `port` is specified as 0, the OS will choose an unused port.
#
# Default:
# port = 0
#
# Examples:
# port = 1234

# The port to use for the web UI.
#
# Can also be specified via the `--http-port` or `-H` command-line options, or
# via the MAELSTROM_BROKER_HTTP_PORT environment variable.
#
# If `http-port` is specified as 0, the OS will choose an unused port.
#
# Default:
# http-port = 0
#
# Examples:
# http-port = 8888

# The directory to use for the cache.
#
# Can also be specified via the `--cache-root` or `-r` command-line options, or
# via the MAELSTROM_BROKER_CACHE_ROOT environment variable.
#
# If this directory doesn't exist, the broker will attempt to create it when
# starting. If not provided, the default cache root will be used from the XDG
# specification.
#
# Examples:
# cache-root = "/home/neal/.cache/maelstrom-broker"

# The target amount of disk space to use for the cache, in bytes. This bound
# won't be followed strictly, so it's best to be conservative
#
# Can also be specified via the `--cache-size` or `-s` command-line options, or
# via the MAELSTROM_BROKER_CACHE_SIZE environment variable.
#
# Default:
# cache-size = "1 GB"
#
# Examples:
# cache-size = 1000000000
# cache-size = "1000000000"
# cache-size = "1.2 GiB"

# The minimum log level to output.
#
# Can also be specified via the `--log-level` or `-l` command-line options, or
# via the MAELSTROM_BROKER_LOG_LEVEL environment variable.
#
# Possibilities: "error", "warning", "info", and "debug"
#
# Default:
# log-level = "info"
#
# Examples:
# log-level = "debug"
