[package]
name = "maelstrom-fuse"
description = "FUSE filesystems for use with Maelstrom"
documentation.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
fuser.workspace = true
futures.workspace = true
maelstrom-linux.workspace = true
tokio = { workspace = true, features = [ "sync" ] }

[dev-dependencies]
clap.workspace = true
