[package]
name = "meticulous-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
figment = { workspace = true }
gethostname = { workspace = true }
meticulous-base = { workspace = true }
meticulous-util = { workspace = true }
nix = { workspace = true }
num_cpus = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
sha2 = { workspace = true }
tar = { workspace = true }
tokio = { workspace = true, features = ["io-util", "net", "process", "rt-multi-thread", "signal", "sync"] }

[dev-dependencies]
anyhow = { workspace = true }
itertools = { workspace = true }
meticulous-test = { workspace = true }
tempfile = { workspace = true }
