[package]
name = "meticulous-worker"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
gethostname = { workspace = true }
meticulous-base = { workspace = true }
meticulous-util = { workspace = true }
nix = { workspace = true }
num_cpus = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
itertools = { workspace = true }
meticulous-test = { workspace = true }
tempfile = { workspace = true }
