[package]
name = "maelstrom-worker"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
anyhow.workspace = true
bumpalo.workspace = true
bytesize.workspace = true
c_str_macro.workspace = true
clap.workspace = true
derive_more.workspace = true
figment.workspace = true
futures.workspace = true
gethostname.workspace = true
maelstrom-base.workspace = true
maelstrom-util.workspace = true
maelstrom-worker-child.workspace = true
nc.workspace = true
netlink-packet-core.workspace = true
netlink-packet-route.workspace = true
nix.workspace = true
num_cpus.workspace = true
rand.workspace = true
serde.workspace = true
serde_with.workspace = true
sha2.workspace = true
slog-async.workspace = true
slog-term.workspace = true
slog.workspace = true
tar.workspace = true
tokio = { workspace = true, features = ["io-util", "net", "process", "rt-multi-thread", "signal", "sync"] }
tuple.workspace = true

[dev-dependencies]
assert_matches.workspace = true
anyhow.workspace = true
itertools.workspace = true
maelstrom-test.workspace = true
serial_test.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["macros"] }
