[package]
name = "meticulous-prototypes"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
flate2 = { workspace = true }
meticulous-base = { workspace = true }
sha2 = { workspace = true }
tar = { workspace = true }
