[package]
name = "meticulous-web"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
console_error_panic_hook = { workspace = true }
eframe = { workspace = true }
egui = { workspace = true }
futures = { workspace = true }
gloo-net = { workspace = true }
gloo-utils = { workspace = true }
meticulous-base = { workspace = true }
wasm-bindgen-futures = { workspace = true }
wasm-bindgen = { workspace = true }
wasm-logger = { workspace = true }

[dependencies.web-sys]
version = "0.3"
features = [
  "Document",
  "Location",
  "WebSocket",
  "Window",
]
