[package]
name = "meticulous-base"
version = "0.1.0"
edition = "2021"

[dependencies]
enum-map.workspace = true
serde.workspace = true
strum.workspace = true

[dev-dependencies]
serde_test.workspace = true
