[package]
name = "meticulous"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
meticulous-ui = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
