# Example config for maelstrom-worker.
#
# Save this as ~/.config/maelstrom/worker/config.toml or wherever you specify
# the config file using the --config-file or -c option.

# The host and port of the broker.
#
# Can also be specified via the `--broker` or `-b` command-line options, or via
# the MAELSTROM_WORKER_BROKER environment variable.
#
# There is no default. This option must be specified.
#
# Examples:
# broker = "localhost:1234"
# broker = "127.0.0.1:1234"
broker = "[::1]:1234"

# The number of job slots available. Most jobs will take one job slot.
#
# Can also be specified via the `--slots` or `-S` command-line options, or via
# the MAELSTROM_WORKER_SLOTS environment variable.
#
# Default: number of machine cores
# Examples:
# slots = 10

# The directory to use for the cache.
#
# Can also be specified via the `--cache-root` or `-r` command-line options, or
# via the MAELSTROM_WORKER_CACHE_ROOT environment variable.
#
# If this directory doesn't exist, the worker will attempt to create it when
# starting. If not provided, the default cache root will be used from the XDG
# specification.
#
# Examples:
# cache-root = "/home/neal/.cache/maelstrom-worker"

# The target amount of disk space to use for the cache, in bytes. This bound
# won't be followed strictly, so it's best to be conservative
#
# Can also be specified via the `--cache-size` or `-s` command-line options, or
# via the MAELSTROM_WORKER_CACHE_SIZE environment variable.
#
# Default:
# cache-size = "1 GB"
#
# Examples:
# cache-size = 1000000000
# cache-size = "1000000000"
# cache-size = "1.2 GiB"

# The maximum amount of bytes to return inline for captured stdout and stderr.
#
# Can also be specified via the `--inline-limit` or `-i`
# command-line options, or via the MAELSTROM_WORKER_INLINE_LIMIT environment
# variable.
#
# Default:
# inline-limit = "1 MB"
#
# Examples:
# inline-limit = 1000000
# inline-limit = "1000000"
# inline-limit = "1.2 MiB"

# The minimum log level to output.
#
# Can also be specified via the `--log-level` or `-l` command-line options, or
# via the MAELSTROM_WORKER_LOG_LEVEL environment variable.
#
# Possibilities: "error", "warning", "info", and "debug"
#
# Default:
# log-level = "info"
#
# Examples:
# log-level = "debug"
