[package]
name = "meticulous-client"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.2.7", features = ["derive", "string", "wrap_help"] }
meticulous = { path = "../../library", version = "^0.1" }
gethostname = "0.4.2"
tokio = { version = "1.28", features = ["full"] }
regex = "1.8.3"
