[package]
name = "meticulous-client"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
meticulous = { workspace = true }
gethostname = { workspace = true }
tokio = { workspace = true }
regex = { workspace = true }
