# Example config for meticulous-client-cli.
#
# Save this as .cache/meticulous-client-cli.toml or wherever you specify the
# config file using the --config-file or -c option.

# The host and port of the broker.
#
# Can also be specified via the `--broker` or `-b` command-line options, or via
# the MAELSTROM_WORKER_BROKER environment variable.
#
# There is no default. This option must be specified.
#
# Examples:
# broker = "localhost:1234"
# broker = "127.0.0.1:1234"
broker = "[::1]:1234"
