
# This directive shows how to use a container image from hub.docker.com.
# This directive will override some things from the other one we defined above, but it will inherit
# mounts and devices from that directive.
#
# [[directives]]
# # Only apply to tests in the "require_full_os" package.
# filter = "package.equals(github.org/maelstrom/requires_full_os)"
#
# # This is the name of the hub.docker.com image to use.
# image.name = "alpline"
#
# # This is the tag to use when downloading the image.
# image.tag = "latest"
#
# # What do we wish to actually utilize from the image?
# # Here we pick environment variables and file-system.
# image.use = [ "environment", "layers" ]
#
# # Add our own layers on top of the image ones to ensure we have a place to mount out special
# # file-systems and devices
# added_layers = [
#    { stubs = [ "/{proc,sys,tmp}/", "/dev/{full,null,random,urandom,zero}" ] },
# ]

# This directive illustrates how to apply a change to one specific test "TestMySpecialTest" in
# package "package_a". Here we change the user and group to be used for this test to 1000.
# Everything else we inherit from the first directive in this file.
#
# [[directives]]
# filter = "package.equals(github.com/my_project/package_a) && name.equals(TestMySpecialTest)"
# user = 1000
# group = 1000

# Some useful filters to use in directives.
#
# # Select all tests from "github.com/my_project/package_a".
# filter = "package.equals(github.com/my_project/package_a)"
#
# # Select a test named "TestMyTest" from any package.
# filter = "name.equals(TestMyTest)"
#
# # Select tests ending with "MyTest" from any package.
# filter = "name.ends_with(MyTest)"
#
# # Select tests from any package named "package_a".
# filter = "package_name.equals(package_a)"
#
# # Select tests from the package at path "pkgs/a".
# filter = "package_path.equals(pkgs/a)"
#
# # Select tests from the package at root
# filter = "package_path.equals()"
