[package]
name = "meticulous-cargo-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
cargo_metadata = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
console = { workspace = true }
indicatif = { workspace = true }
lddtree = { workspace = true }
meticulous-base = { workspace = true }
meticulous-client = { workspace = true }
meticulous-util = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
tar = { workspace = true }
unicode-truncate = { workspace = true }
unicode-width = { workspace = true }

[dev-dependencies]
assert_matches = { workspace = true }
bincode = { workspace = true }
enum-map = { workspace = true }
serde = { workspace = true }
tempfile = { workspace = true }
meticulous-broker = { path = "../meticulous-broker" }
meticulous-worker = { path = "../meticulous-worker" }

[[bin]]
name = "cargo-metest"
path = "src/main.rs"
