[package]
name = "meticulous-cargo-test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
cargo_metadata = { workspace = true }
clap = { workspace = true }
colored = { workspace = true }
console = { workspace = true }
indicatif = { workspace = true }
meticulous-base = { workspace = true }
meticulous-client = { workspace = true }
meticulous-util = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
unicode-truncate = { workspace = true }
unicode-width = { workspace = true }

[[bin]]
name = "cargo-metest"
path = "src/main.rs"
