steps:
  - name: Update the Maelstrom Statistics Spreadsheet
    with:
      gsheet_service_account: ${{ secrets.GSHEET_SERVICE_ACCOUNT }}
  - shell: bash
    env:
      GSHEET_SERVICE_ACCOUNT: ${{ secrets.GSHEET_SERVICE_ACCOUNT }}
    run: |
      scripts/update-stats-spreadsheet.sh $GSHEET_SERVICE_ACCOUNT $GITHUB_TOKEN
